# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

variables:
  - group: node-demo-var-group

resources:
      containers:
      - container: mongodb
        image: mongo:3
        ports:
        - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: $(MONGO_INITDB_ROOT_USERNAME)
          MONGO_INITDB_ROOT_PASSWORD: $(MONGO_INITDB_ROOT_PASSWORD)

stages:
- stage: TEST
  jobs:
  - job:
    pool:
      vmImage: 'ubuntu-16.04'

    services:
      mongodb: mongodb

    steps:

    - script: ls -l /home/vsts/work/1/s
      displayName: Confirm Source Directory Contents
      condition: always()
    - task: UniversalPackages@0
      inputs:
        command: 'publish'
        publishDirectory: '$(Build.ArtifactStagingDirectory)'
        feedsToUsePublish: 'internal'
        vstsFeedPublish: '5231d8a1-0c0d-4c0c-a48a-672567c57865'
        vstsFeedPackagePublish: 'azure-pipeline-yarn-cache'
        versionOption: 'patch'
    - task: RestoreAndSaveCache@1
      inputs:
        keyfile: '**/yarn.lock, **/package-lock.json, !**/node_modules/**/package-lock.json, !**/.*/**/package-lock.json'
        targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
        vstsFeed: '5231d8a1-0c0d-4c0c-a48a-672567c57865'
        platformIndependent: true
    - task: YarnInstaller@3
      inputs:
        versionSpec: '1.x'
      displayName: Install Yarn

#    - task: Npm@1
#      inputs:
#        command: 'custom'
#        workingDir: '/home/vsts/work/1/s'
#        customCommand: 'install newman'
#      condition: ne(variables['CacheRestored'], 'true')
#      displayName: Install Newman

    - task: Yarn@3
      inputs:
        projectDirectory: '/home/vsts/work/1/s'
        arguments: 'run start & sleep 5'
        productionMode: true
      displayName: Start Yarn...

    - script: curl http://localhost:3000/api/tags
      displayName: ...To Get API Tags

    - task: Yarn@3
      env:
        NODE_ENV: $(NODE_ENV)
        MONGODB_URI: $(MONGODB_URI)
      inputs:
        projectDirectory: '/home/vsts/work/1/s'
        arguments: 'run test'
        productionMode: true
      displayName: Test Application

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '*.xml'
        searchFolder: '/home/vsts/work/1/s/results'
      condition: always()
